name: Slack
on:
  workflow_run:
    workflows: [CI, Deploy]
    types: [completed]
    branches: [main]
jobs:
  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    uses: hypothesis/workflows/.github/workflows/slack.yml@main
    with:
      message: ${{ github.event.workflow_run.workflow.name }} failed on main
    secrets: inherit
