name: Test posting to Slack
on:
  workflow_dispatch:
jobs:
  Slack:
    runs-on: ubuntu-latest
    steps:
    - name: Test posting to Slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'testing-github-actions-slack-bot'
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
